# Generated by Django 5.2.3 on 2025-07-01 19:01

# Migration to rename fields and add new fields to Product and PriceHistory models.
# Improves clarity and adds tracking for scraping failures and last checked time.

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        # Rename scraper_source to source in PriceHistory
        migrations.RenameField(
            model_name='pricehistory',
            old_name='scraper_source',
            new_name='source',
        ),
        # Add last_checked field to Product for tracking last check timestamp
        migrations.AddField(
            model_name='product',
            name='last_checked',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        # Add scrape_failures field to Product for error tracking
        migrations.AddField(
            model_name='product',
            name='scrape_failures',
            field=models.IntegerField(default=0),
        ),
        # Make last_scraped nullable for flexibility
        migrations.AlterField(
            model_name='product',
            name='last_scraped',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
