# Generated by Django 5.2.3 on 2025-07-01 19:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricehistory',
            old_name='scraper_source',
            new_name='source',
        ),
        migrations.AddField(
            model_name='product',
            name='last_checked',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='scrape_failures',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='last_scraped',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
