# Generated by Django 5.2.3 on 2025-07-02 15:14

# Migration to update DealAlert model options for ordering and verbose name.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_scraper_source_pricehistory_source_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dealalert',
            options={'ordering': ['-created_at'], 'verbose_name': 'Deal Alert'},
        ),
    ]
