# Generated by Django 5.2.3 on 2025-07-02 17:27

# Major migration: removes several fields and models for refactoring.
# Cleans up Product, DealAlert, PriceHistory, and TrackedProduct models.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_dealalert_options'),
    ]

    operations = [
        # Remove tracked_product from DealAlert
        migrations.RemoveField(
            model_name='dealalert',
            name='tracked_product',
        ),
        # Remove product from PriceHistory
        migrations.RemoveField(
            model_name='pricehistory',
            name='product',
        ),
        # Remove unique constraints and fields from TrackedProduct
        migrations.AlterUniqueTogether(
            name='trackedproduct',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='trackedproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='trackedproduct',
            name='user',
        ),
        # Update Product model options and remove unused fields
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_site_na_e793ec_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_categor_fce6e6_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_is_acti_cb485f_idx',
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='product',
            name='last_checked',
        ),
        migrations.RemoveField(
            model_name='product',
            name='last_scraped',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='scrape_count',
        ),
        migrations.RemoveField(
            model_name='product',
            name='scrape_failures',
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.URLField(),
        ),
        migrations.AlterModelTable(
            name='product',
            table=None,
        ),
        # Delete obsolete models
        migrations.DeleteModel(
            name='DealAlert',
        ),
        migrations.DeleteModel(
            name='PriceHistory',
        ),
        migrations.DeleteModel(
            name='TrackedProduct',
        ),
    ]
