# Generated by Django 5.2.3 on 2025-07-03 00:03

# Migration to update Product model options and site_name field.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_trackedproduct_pricealert_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AlterField(
            model_name='product',
            name='site_name',
            field=models.CharField(max_length=100),
        ),
    ]
