# Generated by Django 5.2.3 on 2025-07-04 01:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_options_alter_product_site_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='trackedproduct',
            name='notes',
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='target_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_categories',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pricealert',
            name='alert_type',
            field=models.CharField(choices=[('price_drop', 'Price Drop'), ('target_reached', 'Target Price Reached'), ('stock_available', 'Back in Stock')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pricealert',
            name='tracked_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='products.trackedproduct'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('electronics', '📱 Electronics'), ('clothing', '👕 Fashion & Clothing'), ('home', '🏠 Home & Garden'), ('books', '📚 Books'), ('sports', '⚽ Sports & Outdoors'), ('beauty', '💄 Beauty & Health'), ('gaming', '🎮 Gaming'), ('automotive', '🚗 Automotive'), ('toys', '🧸 Toys & Games')], default='electronics', max_length=50),
        ),
        migrations.AlterField(
            model_name='trackedproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracked_by', to='products.product'),
        ),
    ]
