# Generated by Django 5.2.3 on 2025-07-05 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_options_remove_trackedproduct_notes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricealert',
            old_name='alert_threshold',
            new_name='target_price',
        ),
        migrations.AlterUniqueTogether(
            name='pricealert',
            unique_together={('tracked_product', 'target_price')},
        ),
        migrations.AddField(
            model_name='pricealert',
            name='is_triggered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pricealert',
            name='triggered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pricealert',
            name='tracked_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.trackedproduct'),
        ),
        migrations.RemoveField(
            model_name='pricealert',
            name='alert_type',
        ),
    ]
