# Generated by Django 5.2.3 on 2025-07-05 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_rename_alert_threshold_pricealert_target_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricealert',
            name='tracked_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_alerts', to='products.trackedproduct'),
        ),
    ]
