# Generated by Django 5.2.3 on 2025-07-07 14:23

# Migration to update UserProfile model options and notification frequency field.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_pricealert_tracked_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='preferred_categories',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notification_frequency',
            field=models.CharField(choices=[('instant', 'Instant'), ('daily', 'Daily Summary'), ('weekly', 'Weekly Summary')], default='instant', max_length=20),
        ),
    ]
