# Generated by Django 5.0.6 on 2025-07-13 00:27

# Migration to add WhatsApp notification fields to UserProfile.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='whatsapp_notifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='notification_frequency',
            field=models.CharField(choices=[('immediate', 'Immediate'), ('daily', 'Daily Summary'), ('weekly', 'Weekly Summary')], default='immediate', max_length=10),
        ),
    ]
