# Generated by Django 5.0.6 on 2025-07-13 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_userprofile_whatsapp_notifications_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricealert',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='pricealert',
            name='tracked_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.trackedproduct'),
        ),
    ]
