# Generated by Django 5.0.6 on 2025-07-15 17:09

# Migration to remove target_price from Product and update several fields for flexibility.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_userprofile_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='target_price',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='current_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='site_name',
            field=models.CharField(max_length=255),
        ),
    ]
